### ISSUE TITLE
[feature] correct css floating point by rounding baseSpacing result

### ISSUE THREAD

**Issue by daniellizik** [kyleshevlin/shevyjs#8]
It's possible to end up with values like `15.555555557px` with `baseSpacing`. My company uses shevyjs in multiple projects and we're repeating lots of logic with correcting floating point errors by rounding to two significant figures.

Could you provide an option in the constructor to round to a configurable number of decimal places? For instance

```js
const shevy = new Shevy({
  baseFontSize: '15px',
  baseFontScale: 'majorThird'
});
shevy.baseSpacing(1.73); // 25.30125px 

const roundedShevy = new Shevy({
  baseFontSize: '15px',
  baseFontScale: 'majorThird',
  roundTo: 2
});
roundedShevy.baseSpacing(1.73); // 25.30px 
```
I can open a PR if you want to include this option.

**Comment by kyleshevlin** [comment]
Hey Daniel, cool to hear that your company uses the project. There are a few ways I can see tackling this problem, but the one closest to what you expressed I think would require at 2 configuration options. The first, which you have as `roundTo`, might be better as `roundingPrecision`, would be an `number`. The second, so that we don't introduce a breaking change to the API, is `useRounding`, would be a `boolean` that defaults to `false`.

I would welcome a PR for this.
